export const CATEGORIES = {
  // The order should correspond with the array returned by the backend
  DApp: 10,
  DEX: 10,
  DeFi: 5,
  'Ethereum Foundation': 0,
  Exchange: 5,
  Gambling: 50,
  Game: 20,
  Hack: 100,
  'ICO Wallet': 20,
  Mining: 0,
  Mixer: 50,
  Other: 20,
  Scam: 100,
  'Stable Coin': 20,
  'Token Contract': 20,
};

export const CATEGORIES_COLOR = {
  DApp: '#808080',
  DEX: '#40E0D0',
  DeFi: '#800080',
  'Ethereum Foundation': '#C0C0C0',
  'Exchange Withdrawal-Wallet': '#00CCCC',
  Exchange: '#00FFFF',
  'Exchange Deposit-Wallet': '#00CCCC',
  'Exchange Multi-Wallet': '#00CCCC',
  Gambling: '#008000',
  Game: '#0000FF',
  Hack: '#FF0000',
  'ICO Wallet': '#808000',
  Mining: '#000080',
  Mixer: '#FFA500',
  Other: '#008080',
  'Exchange-User': '#66DDAA',
  'Mining-User': '#1974D2',
  Scam: '#800000',
  'Stable Coin': '#00FF00',
  'Token Contract': '#000000',
};

export const ENTITIES = [
  '0x Ecosystem',
  '0xUniverse',
  '2Miners',
  '2Miners-User',
  'ABCC',
  'ABCC-User',
  'ALTpool',
  'ALTpool-User',
  'Advertising',
  'AirSwap',
  'Allbit',
  'AlphaPool',
  'AlphaPool-User',
  'AntPool',
  'AntPool-User',
  'BTC.com Pool',
  'BTC.com Pool-User',
  'BaikalMine',
  'BaikalMine-User',
  'Bancor',
  'Basic Attention Token',
  'BeePool',
  'BeePool-User',
  'Bgogo',
  'Bgogo-User',
  'Bilaxy',
  'Bilaxy-User',
  'Binance',
  'Binance-User',
  'BinanceSG',
  'BinanceSG-User',
  'BitClubPool',
  'BitClubPool-User',
  'Bitbox',
  'Bitbox-User',
  'Bitfinex',
  'Bitfinex-User',
  'Bithumb',
  'Bithumb-User',
  'Bitmart',
  'Bitmart-User',
  'Bitmax',
  'Bitmax-User',
  'Bittrex',
  'Bittrex-User',
  'Blockchain Cuties',
  'Bloom',
  'Bw Pool',
  'Bw Pool-User',
  'COSS.io',
  'Celsius Network',
  'Chibi Fighters',
  'Cobinhood',
  'Cobinhood-User',
  'CoinMine',
  'CoinMine-User',
  'Coinbit',
  'Coinhako',
  'Coinhako-User',
  'Coinotron',
  'Coinotron-User',
  'Cold Wallet',
  'Cold Wallet-User',
  'Compound',
  'Compromised',
  'Cruxpool',
  'Cruxpool-User',
  'CryptoBots',
  'CryptoDozer',
  'CryptoKitties',
  'CryptoRome',
  'CryptoSaga',
  'CryptoWars',
  'Cryptopia Compromised',
  'Cryptopia Hack',
  'Cryptopia-User',
  'DAI',
  'DeFi',
  'Decentraland',
  'Dex',
  'Donate',
  'Dragonereum',
  'DwarfPool',
  'DwarfPool-User',
  'ENS',
  'EthashPool',
  'EthashPool-User',
  'EtherDelta Hack',
  'EtherDig',
  'EtherDig-User',
  'Etheremon',
  'Ethereum Foundation',
  'EthereumPool',
  'EthereumPool-User',
  'Ethermine',
  'Ethermine-User',
  'Etheroll',
  'Ethpool',
  'Ethpool-User',
  'Evolution Land',
  'ExtremeHash',
  'ExtremeHash-User',
  'EzilPool',
  'EzilPool-User',
  'F2Pool',
  'F2Pool-User',
  'FKPool',
  'FKPool-User',
  'FOAM',
  'Fiat Gateway',
  'Fiat Gateway-User',
  'Flagged by SEC',
  'Fomo3D',
  'GBX',
  'Gambling',
  'Gate.io',
  'Gate.io-User',
  'Gemini',
  'Gemini-User',
  'Genesis Mining',
  'Genesis Mining-User',
  'Gnosis',
  'Gods Unchained',
  'HashON Pool',
  'HashON Pool-User',
  'Heist',
  'High Risk',
  'HitBTC',
  'HitBTC-User',
  'Hiveon Pool',
  'Hiveon Pool-User',
  'Hotbit',
  'Hotbit-User',
  'Huixingpool',
  'Huixingpool-User',
  'Huobi',
  'Huobi Mining Pool',
  'Huobi-User',
  'Hydro Protocol',
  'Hyper Dragons',
  'ICO Wallets',
  'IDEX',
  'Kraken',
  'Kraken-User',
  'Kryptono',
  'Kryptono-User',
  'KuCoin',
  'KuCoin-User',
  'KuveraPool',
  'LAToken',
  'LAToken-User',
  'LORDLESS',
  'Liqui',
  'Liqui-User',
  'Liquid',
  'Liquid-User',
  'MATPool',
  'MATPool-User',
  'Maker',
  'Matic Network',
  'MaxHash',
  'MaxHash-User',
  'MegaCryptoPolis',
  'Melon',
  'Minerall Pool',
  'Minerall Pool-User',
  'Mining',
  'MiningPoolHub',
  'Mixer',
  'My Crypto Heroes',
  'Neon District',
  'OTC',
  'OTC-User',
  'Okex',
  'Okex-User',
  'Old Contract',
  'OpenSea',
  'Paribu',
  'Paribu-User',
  'Parity Bug',
  'Payment',
  'Phish / Hack',
  'Poloniex',
  'Poloniex-User',
  'Pundi X',
  'QuadrigaCX Compromised',
  'QuadrigaCX-User',
  'Sentinel Protocol',
  'ShapeShift',
  'Spam Token',
  'Storj',
  'Suspicious',
  'Switcheo',
  'Synthetix',
  'Tether',
  'Tezos',
  'Token Contract',
  'Token Sale',
  'TokenSets',
  'Trade.io',
  'Trade.io-User',
  'TrustToken',
  'Uniswap',
  'Uniswap-User',
  'Unsafe',
  'Upbit',
  'Upbit Hack',
  'Upbit-User',
  'Wallet App',
  'White Hat Group',
  'YUNBI',
  'YUNBI-User',
  'ZB.com',
  'ZB.com-User',
  'Zethr',
  'dYdX',
  'firepool',
  'firepool-User',
];
